//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_DAT_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_DAT_HANG()
        {
            this.CTDON_HANG = new HashSet<CTDON_HANG>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
        public Nullable<int> TriGiaDH { get; set; }
        public string PTTT { get; set; }
        public string HTGH { get; set; }
        public Nullable<bool> Dagiao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDON_HANG> CTDON_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
